create database customer_Shopping_behaviour

use customer_Shopping_behaviour

select * from [dbo].[Customer_Shopping_data]

-- Q1. What is the total revenue generated by male vs. female customers?
select * from [dbo].[Customer_Shopping_data]

select gender, sum(purchase_amount) as Total_Revenue
from Customer_Shopping_data
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select avg(purchase_amount) from [dbo].[Customer_Shopping_data]

select customer_id, discount_applied, sum(purchase_amount) as Total_purchase
from Customer_Shopping_data 
group by customer_id, discount_applied, discount_applied
having sum(purchase_amount) > (select avg(purchase_amount) from Customer_Shopping_data) and discount_applied = 'yes'
order by Total_purchase

-- Q3. Which are the top 5 products with the highest average review rating?
select * from [dbo].[Customer_Shopping_data]

select top 5 item_purchased, avg(review_rating) as rating
from Customer_Shopping_data
group by item_purchased
order by avg(review_rating) desc

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select distinct(shipping_type) from [dbo].[Customer_Shopping_data]

select shipping_type, avg(purchase_amount) AVG_Purchasse
from Customer_Shopping_data
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select * from [dbo].[Customer_Shopping_data]

select subscription_status, round(sum(purchase_amount), 2) as Total_purchase,
	round(avg(purchase_amount), 2) as Avg_purchase
from Customer_Shopping_data
group by subscription_status

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from [dbo].[Customer_Shopping_data]

select top 5 item_purchased,
	round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*), 2) as percentag
from Customer_Shopping_data
group by item_purchased
order by percentag desc

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
--and show the count of each segment.
select distinct(previous_purchases) from [dbo].[Customer_Shopping_data]

with cte as(
	select customer_id,
	case	
		when previous_purchases = 1 then 'new'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
	end as Customer_segment
	from Customer_Shopping_data
)
select Customer_segment, count(customer_id) as No_of_Customers
from cte
group by Customer_segment

-- Q8. What are the top 3 most purchased products within each category?
select * from [dbo].[Customer_Shopping_data]

with cte as(
	select category, item_purchased, sum(purchase_amount) as Total_purchase,
	DENSE_RANK() over(partition by category order by sum(purchase_amount) desc) as ranking
	from Customer_Shopping_data
	group by category, item_purchased
)
select *
from cte 
where ranking < 4


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from [dbo].[Customer_Shopping_data]

select subscription_status, count(customer_id) as No_of_Customers
from Customer_Shopping_data
group by subscription_status
having sum(previous_purchases) > 5

select subscription_status, count(customer_id) as No_of_Customers
from Customer_Shopping_data
group by subscription_status
having sum(previous_purchases) < 5

-- Q10. What is the revenue contribution of each age group?
select * from [dbo].[Customer_Shopping_data]

select age_group, sum(purchase_amount)
from Customer_Shopping_data
group by age_group